### PR TITLE
fix unbounded memory usage in `RecvFut::poll_inner`

### LINKED ISSUE #88: Memory leak caused by polling `RecvStream`
`RecvFut` pushes a `hook` thing onto a queue when polled and not ready:

```
wait_lock(&self.receiver.shared.chan).waiting.push_back(hook);
```

Normally, this is all tidied up when the `RecvFut` is dropped, but `RecvStream` will hold onto, and keep polling a `RecvFut` as long as you have the stream open, which can lead to unbounded memory growth.

Below is a simple test case to reproduce. All we do is poll a stream continuously in a loop, waiting for messages to arrive (while assuming here that messages are coming in from other sources, too, so that we keep polling).

If you run this, you'll see the memory usage in `top` increase quickly into hundreds of megs.

**main.rs**

```
use futures::StreamExt;

#[tokio::main]
async fn main() {
    let (tx, rx) = flume::unbounded::<()>();
    let mut rx_stream = rx.into_stream();

    loop {
        tokio::select! {
            _ = rx_stream.next() => {

            },
            _ = std::future::ready(()) => {

            }
        }
    }
}
```

**Cargo.toml**

```
[package]
name = "flume-memleak-test"
version = "0.1.0"
edition = "2018"

[dependencies]
flume = "0.10.9"
futures = "0.3.17"
tokio = { version = "1.7.0", features = ["full"] }
```

### PR DESCRIPTION
**Pull request by HippoBaro**
Successive polling of a `RecvFut` led to unbounded allocations of wakers
in an internal VecDeque. This commit fixes the issue such that wakers
are pushed on the queue only if necessary.

This fixes #88

### CODE REVIEW

File: src/async.rs [hunk 1]
```diff
@@ -40,16 +40,20 @@ impl Signal for AsyncSignal {
 }
 
 impl<T> Hook<T, AsyncSignal> {
-    fn update_waker(&self, cx_waker: &Waker) {
+    // Update the hook to point to the given Waker.
+    // Returns whether the hook has been previously awakened
+    fn update_waker(&self, cx_waker: &Waker) -> bool {
```
Comment (vmingchen) [inline src/async.rs:45]: I have a question. Does the lock guard obtained in `self.1.waker.lock().will_wake()` last only in the if statement condition evaluation? Or it last for the whole if-statement including its body?

If it is the latter, I found the code confusing, because we are locking again at Line-48 (`*self.1.waker.lock() = cx_waker.clone()`).

If it is the former, then I am not sure if this is correct in the following race:

    Time  Thread-1 (calling update_waker)             Thread-2 (calling fire)
    t0    execute Line-46 and `woken` is false
    t1    the if at Line-47 evaluate to true
    t2                                                call fire executing Line 33 to 35
    t3    execute Line-48
    t4    execute Line-52

Then, we ended up not calling `cx_waker.wake_by_ref()`. That is at least contradicting with what the comment is trying to avoid.

I also have a question about the comment. Are we really swapping the wakers? What I see is that we just overwrite `self.1.waker` with the new waker, there is no swapping `cx_waker` to the old waker that was previously held in `self.1.waker`.

**Comment by zesterer** [comment]
Thanks for the PR! I'll have the time to look it over in depth in a few hours.

**Comment by zesterer** [comment]
I *think* I'm happy with this, but having not originally authored the code, perhaps @Restioson could give it a brief look over?

File: src/async.rs (hunk 1 above)
Comment (HippoBaro) [reply src/async.rs:45]: @zesterer, I think @vmingchen makes some good points here. I was trying to avoid adding another atomic load here, but it looks like it might be unavoidable to prevent the race described above. 

Could you advise?

**Comment by Restioson** [comment]
> Successive polling of a RecvFut led to unbounded allocations of wakers in an internal VecDeque

Just checking, are you referring to the case of polling a RecvFut when it has not been woken?

File: src/async.rs (hunk 1 above)
Comment (HippoBaro) [reply src/async.rs:45]: Thanks @Restioson! I went ahead and implemented your solution that locks once and holds the guard until the function returns. I did not change the `wake` function since I'm not sure I understand the specifics.

**Comment by HippoBaro** [comment]
> > Successive polling of a RecvFut led to unbounded allocations of wakers in an internal VecDeque
> 
> Just checking, are you referring to the case of polling a RecvFut when it has not been woken?

Yes, that's what I'm referring to. The wakers are only removed from the VecDeque if they are woken up. If you poll spuriously, then the wakers accumulate indefinitely.

**Review by Restioson — APPROVED** [review]

**Review by zesterer — APPROVED** [review]

**Comment by zesterer** [comment]
Thanks for the PR! @HippoBaro do you want me to release a new version with this fix?

**Comment by HippoBaro** [comment]
> Thanks for the PR! @HippoBaro do you want me to release a new version with this fix?

Yeah, a new version would be perfect 👍 Thank you for pulling!

**Comment by zesterer** [comment]
> > Thanks for the PR! @HippoBaro do you want me to release a new version with this fix?
> 
> Yeah, a new version would be perfect +1 Thank you for pulling!

No problem. I've just published `0.10.14`, which includes this fix. Thanks so much!
